import {test,expect} from "@playwright/test";
test("focus timer persists, pauses, and remains readable on every collapsed edge",async({page})=>{
  await page.clock.install({time:new Date("2026-09-08T10:00:00Z")});
  await page.emulateMedia({reducedMotion:"reduce"});
  await page.goto("/tasks.html?single");
  await page.locator("#task-rail").hover();
  await page.getByRole("button",{name:"Focus Get outside for a walk",exact:true}).click();
  await expect(page.locator("#focus-task-title")).toHaveText("Get outside for a walk");
  await expect(page.locator("#task-list")).toBeHidden();
  await page.clock.fastForward(65000);
  await expect(page.locator("#focus-elapsed")).toHaveText("01:05");
  await page.getByRole("button",{name:"Pause focus timer",exact:true}).click();
  await page.clock.fastForward(60000);
  await expect(page.locator("#focus-elapsed")).toHaveText("01:05");
  await page.reload();
  await page.locator("#task-rail").hover();
  await expect(page.locator("#focus-elapsed")).toHaveText("01:05");
  await page.getByRole("button",{name:"Resume focus timer",exact:true}).click();
  await page.clock.fastForward(1500000);
  await expect(page.locator("#focus-state")).toContainText("25 minutes reached");
  await expect(page.locator("#focus-session")).toHaveCSS("border-top-width","0px");
  await expect(page.locator("#focus-pause svg")).toHaveCount(1);
  await expect(page.locator("#focus-pause")).toHaveText("");
  await page.screenshot({path:"test-results/focus-panel.png"});
  for(const edge of ["left","top","bottom","right"]){
    await page.getByRole("button",{name:"Notch settings",exact:true}).click();
    await page.locator('[data-task-edge="'+edge+'"]').click();
    await page.getByRole("button",{name:"Notch settings",exact:true}).click();
    await page.getByRole("button",{name:"Collapse task panel",exact:true}).click();
    await expect(page.locator("#task-panel")).toBeHidden();
    await expect(page.locator("#focus-pill")).toBeVisible();
    const fits=await page.locator("#focus-pill").evaluate(p=>{const a=p.getBoundingClientRect(),b=p.querySelector(".pill-track")!.getBoundingClientRect();return b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom;});
    expect(fits).toBe(true);
    await expect(page.locator("#focus-pill")).toHaveText("");
    const bar=await page.locator(".pill-track").boundingBox();
    expect(Math.max(bar!.width,bar!.height)).toBeGreaterThan(90);
    expect(Math.min(bar!.width,bar!.height)).toBeGreaterThan(6);
    await page.screenshot({path:"test-results/focus-"+edge+".png"});
    await page.locator("#focus-pill").click();
  }
  await page.getByRole("button",{name:"End focus session",exact:true}).click();
  await expect(page.locator("#focus-session")).toBeHidden();
  await expect(page.locator("#task-list")).toBeVisible();
});
